<div class="page-title">
    <h1>My Observed Products</h1>
</div>
<?php $list = $this->getProducts(); ?>
<?php if (!empty($list)): ?>
    <table class="data-table" style="width: 500px; margin: auto">
        <thead>
            <tr class="first">
                <th style="width: 100px">Product ID</th>
                <th>Product Name</th>
            </tr>
        </thead>

        <?php foreach ($list as $product) { ?>
            <tr class="first">
                <th style="text-align: center"><?php echo $product->getId() ?></th>
                <th><?php echo $product->getName() ?></th>
            </tr>
        <?php } ?>
    </table>
<?php else: ?>
    <p>You don't have any observed products.</p>
<?php endif; ?>

<div class="buttons-set">
    <p class="back-link">
        <a href="#" onClick="history.back()">
            <small>« </small>Back
        </a>
    </p>
</div>
